:scrollbar:
:data-uri:
:toc2:
:linkattrs:


= GPU Workshop Ansible:  VM

:numbered:

== Purpose
The purpose of this ansible is to automate & document the configuration of a RHEL 9 virtual machine to support GPU enabled data science tasks.


This workshop is based on using the precompiled
nvidia drivers that match a specific Red Hat kernel release.

== Pre-reqs

. *ansible*

.. Ansible needs to be installed on the local host machine. ie:
+
-----
# dnf install ansible
-----

.. In addition, the link:https://docs.ansible.com/ansible/latest/collections/ansible/posix/firewalld_module.html[ansible-posix collection] is also needed. ie:
+
-----
# dnf install ansible-collection-ansible-posix.noarch
-----

. *RHEL9 virtual machine*

.. Operating system user
+
Operating system user needs to be enabled with ability to sudo.
+
In addition, ssh access via public/private keys needs to be enabled for this user.

.. Subscription-Manager
+
All VMs need to already have access to base RHEL 9 dnf/yum repositories.

.. Storage
+
The NVIDIA drivers that are installed (as part of this ansible) require at least 20GB allocated to the `/` filesystem.

. *RHEL9 localhost example*

.. Login to the RHEL9 and assume that you have `sudo` privileges with a password.

.. Create the `inventory` file and set the user name.
+
```
[local]
localhost ansible_connection=ssh  ansible_user=<change-me>
```

.. Create a python virtual environment.
+
```
$ python -m venv ~/venv
$ source ~/venv/bin/activate
$ pip install pip ansible -Uq
```

.. Run the ansible playbook as noted below.

== Procedure

. Clone this git project to your local disk and change into this directory.
+
-----
$ cd ansible/vm
-----

. Copy `inventory.example` :
+
-----
$ cp inventory.example inventory
-----
+
Make changes to `inventory` file as needed.
+
Pay particular attention to `changeme` configs.

. Execute:
+
-----
$ ansible-playbook -i inventory vm_update.yml
-----


