---

- hosts: all
  become: true
  tasks:

  - name: Update all installed packages using YUM module
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - name: Remove packages not needed anymore
    yum:
      autoremove: yes

  - name: Reboot when packages were updated
    reboot:
    when: yum_update_status.changed

  - name: Add repositories
    ansible.builtin.yum_repository:
      name: epel
      description: EPEL YUM repo
      gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
      metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
  - name: Add RHEL/EPEL packages
    dnf:
      name:
        - kernel-devel
        - kernel-headers
        - gcc
        - make
        - dkms
        - acpid
        - libglvnd-glx
        - libglvnd-opengl
        - libglvnd-devel
        - pkgconfig
        - firewalld
        - python3-firewall
        - podman-docker
        - skopeo
        - python-pip
        - git
        - java-11-openjdk-devel
        - maven
      state: present
    
  - ansible.builtin.yum_repository:
      name: cuda-rhel9-x86_64
      description: NVIDIA repo
      gpgcheck: false
      baseurl: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64

  - name: Add NVIDIA driver packages
    dnf:
      name:
        - '@nvidia-driver:latest-dkms'
      state: installed

  - name: Check nvidia-smi
    shell: >
      nvidia-smi
    register: nvidia_smi
  - debug:
      msg: "{{ nvidia_smi.stdout_lines }}"

  - name: Add CUDA packages
    dnf:
      name:
        - cuda-11-8
        - libnccl
        - libcudnn8
        - libcusparse-11-8
        - libcublas-11-8
        - libcufft-11-8
        - cuda-cudart-11-8
        - mesa-libGLU
        - freeglut
      state: present


  - name: Open firewall ports
    ansible.posix.firewalld:
      port: 8000-9999/tcp
      permanent: yes
      state: enabled

