---

- hosts: all
  become: true
  tasks:

  - name: Print OS major version
    debug: 
      msg: "OS major version = {{ ansible_distribution_major_version }}"

  - set_fact: cuda_version=11-3
    when: cuda_version is undefined 

  - name: Update all installed packages using YUM module
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - name: Remove packages not needed anymore
    yum:
      autoremove: yes

  - name: Reboot after packages have been updated
    reboot:
    when: yum_update_status.changed

  - name: Register for EPEL package repository
    ansible.builtin.yum_repository:
      name: epel
      description: EPEL YUM repo
      gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
      metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-source-8&arch=$basearch&infra=$infra&content=$contentdir

  # TO-DO:  Consider executing the equivalent:   sudo dnf groupinstall --with-optional "Development Tools"
  - name: Add RHEL/EPEL packages
    dnf:
      name:
        - kernel-devel
        - kernel-headers
        - gcc
        - make
        - dkms
        - acpid
        - libglvnd-glx
        - libglvnd-opengl
        - libglvnd-devel
        - pkgconfig
        - firewalld
        - python3-firewall
        - podman-docker
        - skopeo
        - python3-pip
        - git
        - java-17-openjdk-devel
        - maven
      state: present
    
  - name: Register for NVIDIA package repository
    ansible.builtin.yum_repository:
      name: cuda-rhel{{ ansible_distribution_major_version }}-x86_64
      description: NVIDIA repo
      gpgcheck: false
      baseurl: https://developer.download.nvidia.com/compute/cuda/repos/rhel{{ ansible_distribution_major_version }}/x86_64

  - name: Add NVIDIA driver packages
    dnf:
      name:
        - '@nvidia-driver:latest-dkms'
      state: installed

  - name: View nvidia-smi (System Management Interface) regarding GPU related hardware details
    shell: >
      nvidia-smi
    register: nvidia_smi
  - debug:
      msg: "{{ nvidia_smi.stdout_lines }}"

  - name: Add CUDA packages
    dnf:
      name:
        - cuda-{{ cuda_version }}
        - libnccl
        - libcudnn8
        - libcusparse-{{ cuda_version }}
        - libcublas-{{ cuda_version }}
        - libcufft-{{ cuda_version }}
        - cuda-cudart-{{ cuda_version }}
        - mesa-libGLU
        - freeglut
      state: present


  - name: Open firewall ports
    ansible.posix.firewalld:
      port: 8000-9999/tcp
      permanent: true
      state: enabled
      zone: public
  - shell: |
      firewall-cmd --reload
